# Import needed modules

In [1]:
# Import the stopwords module from the Natural Language Toolkit (nltk) corpus.
from nltk.corpus import stopwords #you can remove stop words for speed
# Import the cosine_distance function from the nltk.cluster.util module.
# This function is used to calculate the cosine distance between two vectors.
from nltk.cluster.util import cosine_distance
# Import the numpy library and assign it the alias 'np'.
# Numpy is a library for efficient numerical computation in Python.
import numpy as np
# Import the networkx library.
# NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
import networkx as nx

# Open file and split into sentences

In [4]:
# Importing data from data set to variable 'file' 
file = open("C:\\Users\\tejas\\Downloads\\Assignment Story.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

In [5]:
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Il était une fois, dans un pays très lointain, un royaume magique caché au plus profond d’une forêt dense
Le royaume s'appelait «Textoria» et était gouverné par un roi sage et juste nommé «Nltk»
Le roi Nltk était connu dans tout le pays pour sa remarquable capacité à comprendre et à analyser la langue de ses sujets.



# Printing list of Sentences

In [6]:
print("Sentences are ", sentences)

Sentences are  [['Il', 'était', 'une', 'fois,', 'dans', 'un', 'pays', 'très', 'lointain,', 'un', 'royaume', 'magique', 'caché', 'au', 'plus', 'profond', 'd’une', 'forêt', 'dense'], ['Le', 'royaume', "s'appelait", '«Textoria»', 'et', 'était', 'gouverné', 'par', 'un', 'roi', 'sage', 'et', 'juste', 'nommé', '«Nltk»'], ['Le', 'roi', 'Nltk', 'était', 'connu', 'dans', 'tout', 'le', 'pays', 'pour', 'sa', 'remarquable', 'capacité', 'Ã\xa0', 'comprendre', 'et', 'Ã\xa0', 'analyser', 'la', 'langue', 'de', 'ses', 'sujets.\n']]


# Function to calculate similarity

In [7]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix

In [8]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

In [9]:
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],
sentences[idx2])

In [10]:
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.21170245 0.12598816]
 [0.21170245 0.         0.28005602]
 [0.12598816 0.28005602 0.        ]]


# Getting the pagerank scores

In [11]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.2799345218306228, 1: 0.39168645855142875, 2: 0.32837901961794824}


# Sort sentences by pagerank

In [12]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.39168645855142875, ['Le', 'royaume', "s'appelait", '«Textoria»', 'et', 'était', 'gouverné', 'par', 'un', 'roi', 'sage', 'et', 'juste', 'nommé', '«Nltk»']), (0.32837901961794824, ['Le', 'roi', 'Nltk', 'était', 'connu', 'dans', 'tout', 'le', 'pays', 'pour', 'sa', 'remarquable', 'capacité', 'Ã\xa0', 'comprendre', 'et', 'Ã\xa0', 'analyser', 'la', 'langue', 'de', 'ses', 'sujets.\n']), (0.2799345218306228, ['Il', 'était', 'une', 'fois,', 'dans', 'un', 'pays', 'très', 'lointain,', 'un', 'royaume', 'magique', 'caché', 'au', 'plus', 'profond', 'd’une', 'forêt', 'dense'])]


# Pick the top “n” sentences

In [13]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 1


# Printing Summary

In [14]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Le royaume s'appelait «Textoria» et était gouverné par un roi sage et juste nommé «Nltk»


# Using Different Languages

# Dutch

# Open file and split into sentences

In [15]:
# Importing data from data set to variable 'file' 
file = open("C:\\Users\\tejas\\Downloads\\Dutch Story.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

In [16]:
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Er was eens, in een land ver, ver weg, een magisch koninkrijk diep verborgen in een dicht bos
Het koninkrijk heette 'Textoria' en werd geregeerd door een wijze en rechtvaardige koning genaamd 'Nltk'
Koning Nltk stond in het hele land bekend om zijn opmerkelijke vermogen om de taal van zijn onderdanen te begrijpen en te analyseren.



# Printing list of Sentences

In [17]:
print("Sentences are ", sentences)

Sentences are  [['Er', 'was', 'eens,', 'in', 'een', 'land', 'ver,', 'ver', 'weg,', 'een', 'magisch', 'koninkrijk', 'diep', 'verborgen', 'in', 'een', 'dicht', 'bos'], ['Het', 'koninkrijk', 'heette', "'Textoria'", 'en', 'werd', 'geregeerd', 'door', 'een', 'wijze', 'en', 'rechtvaardige', 'koning', 'genaamd', "'Nltk'"], ['Koning', 'Nltk', 'stond', 'in', 'het', 'hele', 'land', 'bekend', 'om', 'zijn', 'opmerkelijke', 'vermogen', 'om', 'de', 'taal', 'van', 'zijn', 'onderdanen', 'te', 'begrijpen', 'en', 'te', 'analyseren.\n']]


# Function to calculate similarity

In [18]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix

In [19]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

In [20]:
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],
sentences[idx2])

In [21]:
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.1902606  0.10925356]
 [0.1902606  0.         0.18015094]
 [0.10925356 0.18015094 0.        ]]


# Getting the pagerank scores

In [22]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.31415776925702044, 1: 0.3809512199286362, 2: 0.3048910108143429}


# Sort sentences by pagerank

In [23]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.3809512199286362, ['Het', 'koninkrijk', 'heette', "'Textoria'", 'en', 'werd', 'geregeerd', 'door', 'een', 'wijze', 'en', 'rechtvaardige', 'koning', 'genaamd', "'Nltk'"]), (0.31415776925702044, ['Er', 'was', 'eens,', 'in', 'een', 'land', 'ver,', 'ver', 'weg,', 'een', 'magisch', 'koninkrijk', 'diep', 'verborgen', 'in', 'een', 'dicht', 'bos']), (0.3048910108143429, ['Koning', 'Nltk', 'stond', 'in', 'het', 'hele', 'land', 'bekend', 'om', 'zijn', 'opmerkelijke', 'vermogen', 'om', 'de', 'taal', 'van', 'zijn', 'onderdanen', 'te', 'begrijpen', 'en', 'te', 'analyseren.\n'])]


# Pick the top “n” sentences

In [24]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 2


# Printing Summary

In [25]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Het koninkrijk heette 'Textoria' en werd geregeerd door een wijze en rechtvaardige koning genaamd 'Nltk'. Er was eens, in een land ver, ver weg, een magisch koninkrijk diep verborgen in een dicht bos


# Japanese

# Open file and split into sentences

In [29]:
# Importing data from data set to variable 'file' 
file = open("C:\\Users\\tejas\\Downloads\\Japanese Story.txt", "r", encoding="utf-8")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

In [30]:
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

むかしむかし、遠い遠い国に、深い森の奥深くに隠された魔法の王国がありました。 その王国は「テクストリア」と呼ばれ、「Nltk」という名の賢明で正義の王が統治していました。 Nltk 王は、臣民の言語を理解し分析する驚くべき能力で国中に知られていました。ある日、勇敢な冒険者のグループが森の奥深くに隠された古代の遺物を発見しました。 そのアーティファクトは、蓋に奇妙なシンボルが刻まれた謎の箱でした。 記号には「コサイン距離」と書かれていました。 冒険者たちは好奇心をそそられ、箱を開けて中身を調べてみることにしました。箱を開けるとすぐに、まばゆい光が空間を満たし、箱から人影が現れました。 それは「ナンピー」という名の賢い老魔法使いでした。 ナンピーは数字とパターンの達人であり、現実の構造そのものを操作する力を持っていました。ナンピーは冒険者たちに、自分は何世紀にもわたって箱の中に閉じ込められ、適切な人物が解放してくれるのを待っていたと語った。 彼は、Nltk王の偉大な任務を手伝うためにテクストリアに派遣されたと説明した。 「ストップワーズ」としてのみ知られる闇の勢力が王国を悩ませ始め、言語の構造そのものを破壊する恐れがあった。ストップワードはあまり意味を持たない一般的な言葉でしたが、強力になり、王国中に急速に広まりました。 彼らは言語を破壊しており、Nltk王とその臣下が効果的に意思疎通することを困難にしていました。ナンピーは冒険者たちと力を合わせ、一緒にストップワードを倒すために出発した。 彼らは王国中を旅し、Numpy の力を使って言語を分析し、ストップワードを特定しました。 彼らは旅の途中で、強力な味方である「ネットワークx」という名の勇敢な戦士に出会いました。



# Printing list of Sentences

In [31]:
print("Sentences are ", sentences)

Sentences are  [['\ufeffむかしむかし、遠い遠い国に、深い森の奥深くに隠された魔法の王国がありました。', 'その王国は「テクストリア」と呼ばれ、「Nltk」という名の賢明で正義の王が統治していました。', 'Nltk', '王は、臣民の言語を理解し分析する驚くべき能力で国中に知られていました。ある日、勇敢な冒険者のグループが森の奥深くに隠された古代の遺物を発見しました。', 'そのアーティファクトは、蓋に奇妙なシンボルが刻まれた謎の箱でした。', '記号には「コサイン距離」と書かれていました。', '冒険者たちは好奇心をそそられ、箱を開けて中身を調べてみることにしました。箱を開けるとすぐに、まばゆい光が空間を満たし、箱から人影が現れました。', 'それは「ナンピー」という名の賢い老魔法使いでした。', 'ナンピーは数字とパターンの達人であり、現実の構造そのものを操作する力を持っていました。ナンピーは冒険者たちに、自分は何世紀にもわたって箱の中に閉じ込められ、適切な人物が解放してくれるのを待っていたと語った。', '彼は、Nltk王の偉大な任務を手伝うためにテクストリアに派遣されたと説明した。', '「ストップワーズ」としてのみ知られる闇の勢力が王国を悩ませ始め、言語の構造そのものを破壊する恐れがあった。ストップワードはあまり意味を持たない一般的な言葉でしたが、強力になり、王国中に急速に広まりました。', '彼らは言語を破壊しており、Nltk王とその臣下が効果的に意思疎通することを困難にしていました。ナンピーは冒険者たちと力を合わせ、一緒にストップワードを倒すために出発した。', '彼らは王国中を旅し、Numpy', 'の力を使って言語を分析し、ストップワードを特定しました。', '彼らは旅の途中で、強力な味方である「ネットワークx」という名の勇敢な戦士に出会いました。\n']]


# Function to calculate similarity

In [32]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

# Create the similarity matrix

In [33]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

In [34]:
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],
sentences[idx2])

In [35]:
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.]]


# Getting the pagerank scores

In [36]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 1.0}


# Sort sentences by pagerank

In [37]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(1.0, ['\ufeffむかしむかし、遠い遠い国に、深い森の奥深くに隠された魔法の王国がありました。', 'その王国は「テクストリア」と呼ばれ、「Nltk」という名の賢明で正義の王が統治していました。', 'Nltk', '王は、臣民の言語を理解し分析する驚くべき能力で国中に知られていました。ある日、勇敢な冒険者のグループが森の奥深くに隠された古代の遺物を発見しました。', 'そのアーティファクトは、蓋に奇妙なシンボルが刻まれた謎の箱でした。', '記号には「コサイン距離」と書かれていました。', '冒険者たちは好奇心をそそられ、箱を開けて中身を調べてみることにしました。箱を開けるとすぐに、まばゆい光が空間を満たし、箱から人影が現れました。', 'それは「ナンピー」という名の賢い老魔法使いでした。', 'ナンピーは数字とパターンの達人であり、現実の構造そのものを操作する力を持っていました。ナンピーは冒険者たちに、自分は何世紀にもわたって箱の中に閉じ込められ、適切な人物が解放してくれるのを待っていたと語った。', '彼は、Nltk王の偉大な任務を手伝うためにテクストリアに派遣されたと説明した。', '「ストップワーズ」としてのみ知られる闇の勢力が王国を悩ませ始め、言語の構造そのものを破壊する恐れがあった。ストップワードはあまり意味を持たない一般的な言葉でしたが、強力になり、王国中に急速に広まりました。', '彼らは言語を破壊しており、Nltk王とその臣下が効果的に意思疎通することを困難にしていました。ナンピーは冒険者たちと力を合わせ、一緒にストップワードを倒すために出発した。', '彼らは王国中を旅し、Numpy', 'の力を使って言語を分析し、ストップワードを特定しました。', '彼らは旅の途中で、強力な味方である「ネットワークx」という名の勇敢な戦士に出会いました。\n'])]


# Pick the top “n” sentences

In [38]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 1


# Printing Summary

In [39]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 むかしむかし、遠い遠い国に、深い森の奥深くに隠された魔法の王国がありました。 その王国は「テクストリア」と呼ばれ、「Nltk」という名の賢明で正義の王が統治していました。 Nltk 王は、臣民の言語を理解し分析する驚くべき能力で国中に知られていました。ある日、勇敢な冒険者のグループが森の奥深くに隠された古代の遺物を発見しました。 そのアーティファクトは、蓋に奇妙なシンボルが刻まれた謎の箱でした。 記号には「コサイン距離」と書かれていました。 冒険者たちは好奇心をそそられ、箱を開けて中身を調べてみることにしました。箱を開けるとすぐに、まばゆい光が空間を満たし、箱から人影が現れました。 それは「ナンピー」という名の賢い老魔法使いでした。 ナンピーは数字とパターンの達人であり、現実の構造そのものを操作する力を持っていました。ナンピーは冒険者たちに、自分は何世紀にもわたって箱の中に閉じ込められ、適切な人物が解放してくれるのを待っていたと語った。 彼は、Nltk王の偉大な任務を手伝うためにテクストリアに派遣されたと説明した。 「ストップワーズ」としてのみ知られる闇の勢力が王国を悩ませ始め、言語の構造そのものを破壊する恐れがあった。ストップワードはあまり意味を持たない一般的な言葉でしたが、強力になり、王国中に急速に広まりました。 彼らは言語を破壊しており、Nltk王とその臣下が効果的に意思疎通することを困難にしていました。ナンピーは冒険者たちと力を合わせ、一緒にストップワードを倒すために出発した。 彼らは王国中を旅し、Numpy の力を使って言語を分析し、ストップワードを特定しました。 彼らは旅の途中で、強力な味方である「ネットワークx」という名の勇敢な戦士に出会いました。

